export const OPEN_NAVBAR = 'OPEN_NAVBAR';
export const CHANGE_ADMIN_CONTENT = 'CHANGE_ADMIN_CONTENT';
export const CHANGE_ADMIN_CONTENT_EXTENSION = 'CHANGE_ADMIN_CONTENT_EXTENSION';
export const CHANGE_TABLE = 'CHANGE_TABLE';
export const FETCH_SELECTED = 'FETCH_SELECTED';
